name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  APACHE24: '2.4.53'

jobs:
  apache-24:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.APACHE24 }}
        tags: 2.4,2,latest
        platform: linux/amd64,linux/arm64
  apache-24-alpine313:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.APACHE24 }}
        tags: 2.4-alpine3.13,2-alpine3.13,alpine3.13
        platform: linux/amd64,linux/arm64
